version: 0.2

phases:
  install:
    commands:
      - yum -y install wget
      - wget https://dl.yarnpkg.com/rpm/yarn.repo -O /etc/yum.repos.d/yarn.repo
      - curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
      - yum install yarn
      - yarn --version
      - yarn install
      - yarn lint

cache:
  paths:
    - './node_modules/**/*'
    - './vendor/**/*'